---
- name: install packages including mysql-server
  become: yes
  apt:
    name: ['mysql-server', 'python3-pip']
    state: present

- name: install pymysql
  become: yes
  pip:
    executable: pip3
    name: pymysql
    state: present

- name: add mysql admin user
  become: yes
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: root
    name: "{{ mysql_admin_user }}"
    password: "{{ mysql_admin_pass }}"
    priv: '*.*:ALL'
    host: '%'
    state: present

- name: add regular user
  become: yes
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: root
    name: "{{ mysql_staff_user }}"
    password: "{{ mysql_staff_pass }}"
    priv: 'myclinic.*:DELETE,INSERT,UPDATE,SELECT'
    host: '%'
    state: present
- name: create myclinic database
  become: yes
  mysql_db:
    name: myclinic
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: root

