---
- name: disable cloud-init
  become: yes
  copy:
    dest: /etc/cloud/cloud-init.disabled
    content: ""

- name: modify LS_COLORS
  become: no
  lineinfile:
    dest: ~/.bashrc
    regexp: '^export LS_COLORS='
    line: 'export LS_COLORS=$LS_COLORS:''di=1;32:'''

- name: wait for apt lock
  shell: ps ax | grep '.systemd.daily lock_is_held' | wc -l
  register: apt_lock_result
  until: apt_lock_result.stdout != "3"
  delay: 20
  retries: 60
  tags: wait_for_apt_lock

- name: apt update and upgrade
  become: yes
  apt:
    update_cache: yes
    upgrade: full

